package com.army.adminMovieEro.noticeBoard.model.vo;

import java.sql.Date;

public class noticeVO {
	private int RNUM;
	private String MB_ID;
	private String NOTICE_BOARD_TITLE;
	private String NOTICE_BOARD_CONTENT;
	private Date NOTICE_BOARD_DATE;
	private String NOTICE_BOARD_ORIGINFILENAME; 
	private int NOTICE_BOARD_READCNT;
	private int NOTICE_BOARD_NO;
	private String NOTICE_BOARD_RENAMEFILENAME;
	
	public noticeVO() {}
	
	public noticeVO(int RNUM,String MB_ID, String NOTICE_BOARD_TITLE, String NOTICE_BOARD_CONTENT, Date NOTICE_BOARD_DATE,
			String NOTICE_BOARD_ORIGINFILENAME, int NOTICE_BOARD_READCNT, int NOTICE_BOARD_NO, String NOTICE_BOARD_RENAMEFILENAME) {
		super();
		this.RNUM = RNUM;
		this.MB_ID = MB_ID;
		this.NOTICE_BOARD_TITLE = NOTICE_BOARD_TITLE;
		this.NOTICE_BOARD_CONTENT = NOTICE_BOARD_CONTENT;
		this.NOTICE_BOARD_DATE = NOTICE_BOARD_DATE;
		this.NOTICE_BOARD_ORIGINFILENAME = NOTICE_BOARD_ORIGINFILENAME;
		this.NOTICE_BOARD_READCNT = NOTICE_BOARD_READCNT;
		this.NOTICE_BOARD_NO = NOTICE_BOARD_NO;
		this.NOTICE_BOARD_RENAMEFILENAME = NOTICE_BOARD_RENAMEFILENAME;
	}
	
	
	public noticeVO(String MB_ID, String NOTICE_BOARD_TITLE, String NOTICE_BOARD_CONTENT, Date NOTICE_BOARD_DATE,
			String NOTICE_BOARD_ORIGINFILENAME, int NOTICE_BOARD_READCNT, int NOTICE_BOARD_NO,String NOTICE_BOARD_RENAMEFILENAME) {
		super();
		
		this.MB_ID = MB_ID;
		this.NOTICE_BOARD_TITLE = NOTICE_BOARD_TITLE;
		this.NOTICE_BOARD_CONTENT = NOTICE_BOARD_CONTENT;
		this.NOTICE_BOARD_DATE = NOTICE_BOARD_DATE;
		this.NOTICE_BOARD_ORIGINFILENAME = NOTICE_BOARD_ORIGINFILENAME;
		this.NOTICE_BOARD_READCNT = NOTICE_BOARD_READCNT;
		this.NOTICE_BOARD_NO = NOTICE_BOARD_NO;
		this.NOTICE_BOARD_RENAMEFILENAME = NOTICE_BOARD_RENAMEFILENAME;
	}


	

		//수정을 위한 VO
		public noticeVO(String MB_ID, String NOTICE_BOARD_TITLE, String NOTICE_BOARD_CONTENT,
			int NOTICE_BOARD_NO) {
		super();
		this.MB_ID = MB_ID;
		this.NOTICE_BOARD_TITLE = NOTICE_BOARD_TITLE;
		this.NOTICE_BOARD_CONTENT = NOTICE_BOARD_CONTENT;
		this.NOTICE_BOARD_NO = NOTICE_BOARD_NO;
	}

	
	
	
	

	public int getRNUM() {
			return RNUM;
		}

		public String getMB_ID() {
			return MB_ID;
		}

		public String getNOTICE_BOARD_TITLE() {
			return NOTICE_BOARD_TITLE;
		}

		public String getNOTICE_BOARD_CONTENT() {
			return NOTICE_BOARD_CONTENT;
		}

		public Date getNOTICE_BOARD_DATE() {
			return NOTICE_BOARD_DATE;
		}

		public String getNOTICE_BOARD_ORIGINFILENAME() {
			return NOTICE_BOARD_ORIGINFILENAME;
		}

		public int getNOTICE_BOARD_READCNT() {
			return NOTICE_BOARD_READCNT;
		}

		public int getNOTICE_BOARD_NO() {
			return NOTICE_BOARD_NO;
		}

		public String getNOTICE_BOARD_RENAMEFILENAME() {
			return NOTICE_BOARD_RENAMEFILENAME;
		}

		public void setRNUM(int rNUM) {
			RNUM = rNUM;
		}

		public void setMB_ID(String mB_ID) {
			MB_ID = mB_ID;
		}

		public void setNOTICE_BOARD_TITLE(String nOTICE_BOARD_TITLE) {
			NOTICE_BOARD_TITLE = nOTICE_BOARD_TITLE;
		}

		public void setNOTICE_BOARD_CONTENT(String nOTICE_BOARD_CONTENT) {
			NOTICE_BOARD_CONTENT = nOTICE_BOARD_CONTENT;
		}

		public void setNOTICE_BOARD_DATE(Date nOTICE_BOARD_DATE) {
			NOTICE_BOARD_DATE = nOTICE_BOARD_DATE;
		}

		public void setNOTICE_BOARD_ORIGINFILENAME(String nOTICE_BOARD_ORIGINFILENAME) {
			NOTICE_BOARD_ORIGINFILENAME = nOTICE_BOARD_ORIGINFILENAME;
		}

		public void setNOTICE_BOARD_READCNT(int nOTICE_BOARD_READCNT) {
			NOTICE_BOARD_READCNT = nOTICE_BOARD_READCNT;
		}

		public void setNOTICE_BOARD_NO(int nOTICE_BOARD_NO) {
			NOTICE_BOARD_NO = nOTICE_BOARD_NO;
		}

		public void setNOTICE_BOARD_RENAMEFILENAME(String nOTICE_BOARD_RENAMEFILENAME) {
			NOTICE_BOARD_RENAMEFILENAME = nOTICE_BOARD_RENAMEFILENAME;
		}

	@Override
	public String toString() {
		return "noticeVO [RNUM=" + RNUM + ", MB_ID=" + MB_ID + ", NOTICE_BOARD_TITLE=" + NOTICE_BOARD_TITLE
				+ ", NOTICE_BOARD_CONTENT=" + NOTICE_BOARD_CONTENT + ", NOTICE_BOARD_DATE=" + NOTICE_BOARD_DATE
				+ ", NOTICE_BOARD_ORIGINFILENAME=" + NOTICE_BOARD_ORIGINFILENAME + ", NOTICE_BOARD_READCNT=" + NOTICE_BOARD_READCNT
				+ ", NOTICE_BOARD_NO=" + NOTICE_BOARD_NO + "]";
	}
	
}

