package com.army.adminMovieEro.theaterAddList.model.vo;

import java.sql.Date;

public class theaterVO {

	String RENTAL_SERVICE_INFO; 
	String RENTAL_SERVICE_POSITION ;
	String RENTAL_SERVICE_PRICE ;
	String RENTAL_SERVICE_TITLE ;
	Date RENTAL_SERVICE_STRRTDATE;
	Date RENTAL_SERVICE_FINALDATE;
	int RENTAL_SERVICE_NO;
	
	
	public String getRENTAL_SERVICE_INFO() {
		return RENTAL_SERVICE_INFO;
	}
	public void setRENTAL_SERVICE_INFO(String rENTAL_SERVICE_INFO) {
		RENTAL_SERVICE_INFO = rENTAL_SERVICE_INFO;
	}
	public String getRENTAL_SERVICE_POSITION() {
		return RENTAL_SERVICE_POSITION;
	}
	public void setRENTAL_SERVICE_POSITION(String rENTAL_SERVICE_POSITION) {
		RENTAL_SERVICE_POSITION = rENTAL_SERVICE_POSITION;
	}
	public String getRENTAL_SERVICE_PRICE() {
		return RENTAL_SERVICE_PRICE;
	}
	public void setRENTAL_SERVICE_PRICE(String rENTAL_SERVICE_PRICE) {
		RENTAL_SERVICE_PRICE = rENTAL_SERVICE_PRICE;
	}
	public String getRENTAL_SERVICE_TITLE() {
		return RENTAL_SERVICE_TITLE;
	}
	public void setRENTAL_SERVICE_TITLE(String rENTAL_SERVICE_TITLE) {
		RENTAL_SERVICE_TITLE = rENTAL_SERVICE_TITLE;
	}
	public Date getRENTAL_SERVICE_STRRTDATE() {
		return RENTAL_SERVICE_STRRTDATE;
	}
	public void setRENTAL_SERVICE_STRRTDATE(Date rENTAL_SERVICE_STRRTDATE) {
		RENTAL_SERVICE_STRRTDATE = rENTAL_SERVICE_STRRTDATE;
	}
	public Date getRENTAL_SERVICE_FINALDATE() {
		return RENTAL_SERVICE_FINALDATE;
	}
	public void setRENTAL_SERVICE_FINALDATE(Date rENTAL_SERVICE_FINALDATE) {
		RENTAL_SERVICE_FINALDATE = rENTAL_SERVICE_FINALDATE;
	}
	public int getRENTAL_SERVICE_NO() {
		return RENTAL_SERVICE_NO;
	}
	public void setRENTAL_SERVICE_NO(int rENTAL_SERVICE_NO) {
		RENTAL_SERVICE_NO = rENTAL_SERVICE_NO;
	}
	
	
}
